<?php

define('WPFANCYGALLERY_DB_NAME_HU_FANCY_GALLERY', 'wpfancygallery_hu_fancy_gallery');
define('WPFANCYGALLERY_DB_NAME_HU_FANCY_IMAGES', 'wpfancygallery_hu_fancy_images');
define('WPFANCYGALLERY_GALLERY_PATH', plugin_dir_path(__FILE__));
define('WPFANCYGALLERY_GALLERY_URL', plugin_dir_url(__FILE__));
define('WPFANCYGALLERY_GALLERY_INC_PATH', WPFANCYGALLERY_GALLERY_PATH . 'inc/');
define('WPFANCYGALLERY_GALLERY_INC_URL', WPFANCYGALLERY_GALLERY_URL . 'inc/');
define('WPFANCYGALLERY_GALLERY_ASSETS_URL', WPFANCYGALLERY_GALLERY_INC_URL . 'assets/');
define('WPFANCYGALLERY_GALLERY_ASSETS_ADMIN_URL', WPFANCYGALLERY_GALLERY_ASSETS_URL . 'admin/');
define('WPFANCYGALLERY_GALLERY_ASSETS_ADMIN_JS_URL', WPFANCYGALLERY_GALLERY_ASSETS_ADMIN_URL . 'js/');
define('WPFANCYGALLERY_GALLERY_ASSETS_ADMIN_CSS_URL', WPFANCYGALLERY_GALLERY_ASSETS_ADMIN_URL . 'css/');
define('WPFANCYGALLERY_GALLERY_ASSETS_ADMIN_IMAGES_URL', WPFANCYGALLERY_GALLERY_ASSETS_ADMIN_URL . 'images/');
define('WPFANCYGALLERY_GALLERY_ASSETS_FRONTEND_URL', WPFANCYGALLERY_GALLERY_ASSETS_URL . 'frontend/');
define('WPFANCYGALLERY_GALLERY_ASSETS_FRONTEND_JS_URL', WPFANCYGALLERY_GALLERY_ASSETS_FRONTEND_URL . 'js/');
define('WPFANCYGALLERY_GALLERY_ASSETS_FRONTEND_CSS_URL', WPFANCYGALLERY_GALLERY_ASSETS_FRONTEND_URL . 'css/');
define('WPFANCYGALLERY_GALLERY_INIT_PATH', WPFANCYGALLERY_GALLERY_INC_PATH . 'Init/');
define('WPFANCYGALLERY_GALLERY_TEMPLATE_PATH', WPFANCYGALLERY_GALLERY_INC_PATH . 'templates/');
define('WPFANCYGALLERY_GALLERY_T_ADMIN_PATH', WPFANCYGALLERY_GALLERY_TEMPLATE_PATH . 'admin/');
define('WPFANCYGALLERY_GALLERY_T_FRONT_PATH', WPFANCYGALLERY_GALLERY_TEMPLATE_PATH . 'front/');
define('WPFANCYGALLERY_GALLERY_CONTROLLERS', WPFANCYGALLERY_GALLERY_INC_PATH . 'Controllers/');
define('WPFANCYGALLERY_GALLERY_INC_DB_PATH', WPFANCYGALLERY_GALLERY_INC_PATH . 'DbClasses/');
